version: '3.8'

services:
  db:
    platform: linux/amd64
    # container_name: 'db'
    image: amd64/postgres:14.6
    # restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    # volumes:
    #   - postgres:/var/lib/postgresql
    environment:
      POSTGRES_USER: moeguide
      POSTGRES_PASSWORD: moeguide
      POSTGRES_DB: moeguide

  minio:
    # container_name: minio
    command: ['server', '/data', '--console-address', ':5559', '--certs-dir', '/root/.minio/certs']
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '5559:5559'
    expose:
      - 5559
      - 9000
    # volumes:
    #   - ./minio:/data
    restart: unless-stopped
    env_file:
      - ./.env

  migrator:
    image: minio/mc
    depends_on:
      - minio
    restart: on-failure:5
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 $$MINIO_ROOT_USER $$MINIO_ROOT_PASSWORD;
      mc mb myminio/$${BUCKET_NAME_MAIN}-$${STAGE_NAME};
      # mc cp init_data/* myminio/$${BUCKET_NAME_MAIN}-$${STAGE_NAME};
      "
    # volumes:
    #   - ./datalayer/minio:/init_data
    env_file:
      - ./.env